image: phunehehe/nix
build:
    script:
      - nix-build --no-out-link .
        # Capture the cabal file by nix2cabal
      - nix-shell --run true
    artifacts:
        paths:
          - ./brackets.cabal
variables:
    GIT_SUBMODULE_STRATEGY: recursive
